services:
  - type: web
    name: rational-arcade
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set this in Render dashboard if using database